### PR TITLE
Built for Swift 4.1

### PR DESCRIPTION
**Pull request by hbs-developers**

### CODE REVIEW

**Comment by ashtru** [comment]
We will review this PR, and come back to you soon.

**Comment by RakeshVisa** [comment]
Hi @hatboyzero, thanks for updating the framework to Swift 4.1. Looks like there are some conflicts in your changes. Can you please resolve those conflicts and create a new pull request?. (Please make sure to remove simulator symbols from your framework as it will be issue for Appstore submission).

**Comment by mohammadkalim** [comment]
Kindly accept this pull request so I can integrate into the project.

**Comment by hatboyzero** [comment]
All I did was build the existing code in 4.1 and manually update the binaries in the repository.  "It works for me" (TM), and I don't have write access to merge the pull request, so either use my fork or those of you with appropriate permissions merge it yourself if you need 4.1 support.

**Comment by hatboyzero** [comment]
Unless you see something I don't, I suggest you go ahead and merge the pod, dood.  Cheers.

**Pull request merged**
